<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Content Remove="Data\Checks\August\01-08-2024.json" />
    <Content Remove="Data\Products\Cat.json" />
    <Content Remove="Data\Products\Drinks.json" />
    <Content Remove="Data\Products\Household.json" />
    <Content Remove="Data\Products\Meat.json" />
    <Content Remove="Data\Products\Other.json" />
    <Content Remove="Data\Products\Salty.json" />
    <Content Remove="Data\Products\Sweet.json" />
    <Content Remove="Data\Products\Vegetables.json" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Data\Checks\August\01-08-2024.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Include="Data\Products\Cat.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Include="Data\Products\Drinks.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Include="Data\Products\Household.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Include="Data\Products\Meat.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Include="Data\Products\Other.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Include="Data\Products\Salty.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Include="Data\Products\Sweet.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Include="Data\Products\Vegetables.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" Version="12.4.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.7" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.7">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.4.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CostKeeper.Core\CostKeeper.Core.csproj" />
  </ItemGroup>

</Project>
